"use server";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { validateEmployee } from "@/lib/employee-validation";

async function organizationId() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error("Unauthorized"); const { data } = await supabase.from("users").select("organization_id").eq("id", user.id).single(); if (!data) throw new Error("Organization not found"); return { supabase, id: data.organization_id }; }
export async function createEmployee(formData) { const row = Object.fromEntries(formData); const employee = { employee_id: row.employee_id || undefined, first_name: row.first_name?.trim(), last_name: row.last_name?.trim(), department: row.department || undefined, position: row.position || undefined, email: row.email || undefined, phone_number: row.phone_number || undefined, birthday_month: Number(row.birthday_month), birthday_day: Number(row.birthday_day) }; const errors = validateEmployee(employee); if (errors.length) return { error: errors.join(", ") }; const { supabase, id } = await organizationId(); const { error } = await supabase.from("employees").insert({ ...employee, organization_id: id }); if (error) return { error: error.message }; revalidatePath("/dashboard/employees"); return { success: true }; }
export async function deleteEmployee(id) { const { supabase } = await organizationId(); const { error } = await supabase.from("employees").delete().eq("id", id); if (error) return { error: error.message }; revalidatePath("/dashboard/employees"); return { success: true }; }
export async function importEmployees(rows) { if (rows.length > 500) return { error: "Import up to 500 employees at a time." }; const invalid = rows.map((row, index) => ({ index, errors: validateEmployee(row) })).filter((item) => item.errors.length); if (invalid.length) return { error: `Fix validation errors in ${invalid.length} row(s) before importing.` }; const { supabase, id } = await organizationId(); const { error } = await supabase.from("employees").insert(rows.map(({ employee_id, ...row }) => ({ ...row, employee_id: employee_id || null, organization_id: id }))); if (error) return { error: error.message }; revalidatePath("/dashboard/employees"); return { success: true, count: rows.length }; }
