"use client";
import { useState, useTransition } from "react";
import { X } from "lucide-react";
import { createEmployee } from "@/app/dashboard/employees/actions";

const fieldClass = "mt-1.5 w-full rounded-xl border bg-white px-3 py-2.5 text-sm outline-none focus:border-[#6B5CE7]";
export function AddEmployeeForm() { const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [pending, startTransition] = useTransition(); function submit(formData) { startTransition(async () => { const result = await createEmployee(formData); if (result.error) return setMessage(result.error); setOpen(false); setMessage(""); }); }
  return <><button onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white">Add employee</button>{open && <div className="fixed inset-0 z-50 grid place-items-center bg-ink/30 p-4"><form action={submit} className="relative max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl"><button type="button" onClick={() => setOpen(false)} className="absolute right-5 top-5 rounded-lg p-1 text-slate-500"><X size={20}/></button><h2 className="text-xl font-bold">Add employee</h2><p className="mt-1 text-sm text-slate-500">Add a birthday to begin creating better celebrations.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Label label="First name *"><input required name="first_name" className={fieldClass}/></Label><Label label="Last name *"><input required name="last_name" className={fieldClass}/></Label><Label label="Employee ID"><input name="employee_id" className={fieldClass}/></Label><Label label="Department"><input name="department" className={fieldClass}/></Label><Label label="Position"><input name="position" className={fieldClass}/></Label><Label label="Work email"><input name="email" type="email" className={fieldClass}/></Label><Label label="Birthday month *"><input required name="birthday_month" min="1" max="12" type="number" className={fieldClass}/></Label><Label label="Birthday day *"><input required name="birthday_day" min="1" max="31" type="number" className={fieldClass}/></Label></div>{message && <p className="mt-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-600">{message}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="rounded-xl px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={pending} className="rounded-xl bg-[#6B5CE7] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving…" : "Save employee"}</button></div></form></div>}</>; }
function Label({ label, children }) { return <label className="text-sm font-medium text-slate-700">{label}{children}</label>; }
