create extension if not exists "uuid-ossp";

create table public.organizations (
  id uuid primary key default gen_random_uuid(), name text not null, logo_url text, primary_brand_color text not null default '#6B5CE7', secondary_brand_color text not null default '#17213A', website text, timezone text not null default 'Africa/Lagos', default_email_signature text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.users (
  id uuid primary key references auth.users(id) on delete cascade, organization_id uuid not null references public.organizations(id) on delete cascade, full_name text, role text not null default 'admin' check (role in ('owner','admin','hr_member','viewer')), created_at timestamptz not null default now()
);
create table public.employees (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id text, first_name text not null, last_name text not null, department text, position text, email text, phone_number text, birthday_month smallint not null check (birthday_month between 1 and 12), birthday_day smallint not null check (birthday_day between 1 and 31), photo_url text, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, employee_id)
);
create table public.birthday_reminders (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, reminder_type text not null, scheduled_for timestamptz not null, status text not null default 'pending', sent_at timestamptz);
create table public.birthday_posters (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, employee_id uuid not null references public.employees(id) on delete cascade, message text, image_url text, design_style text, status text not null default 'draft' check (status in ('draft','pending_approval','approved','rejected','sent')), created_by uuid references public.users(id), created_at timestamptz not null default now());
create table public.ai_generations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, user_id uuid references public.users(id), generation_type text not null, input jsonb not null default '{}', output jsonb, created_at timestamptz not null default now());
create table public.email_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, poster_id uuid references public.birthday_posters(id), recipient text not null, status text not null default 'queued', provider_id text, sent_at timestamptz, created_at timestamptz not null default now());
create table public.approval_queue (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, poster_id uuid not null references public.birthday_posters(id) on delete cascade, reviewer_id uuid references public.users(id), decision text check (decision in ('approved','rejected')), notes text, decided_at timestamptz);
create table public.activity_logs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade, actor_id uuid references public.users(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());

alter table public.organizations enable row level security; alter table public.users enable row level security; alter table public.employees enable row level security; alter table public.birthday_reminders enable row level security; alter table public.birthday_posters enable row level security; alter table public.ai_generations enable row level security; alter table public.email_logs enable row level security; alter table public.approval_queue enable row level security; alter table public.activity_logs enable row level security;
create function public.current_organization_id() returns uuid language sql stable security definer set search_path = public as $$ select organization_id from public.users where id = auth.uid() $$;
create policy "Members access their organization" on public.organizations for all using (id = public.current_organization_id()) with check (id = public.current_organization_id());
create policy "Members access their profile" on public.users for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation employees" on public.employees for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation reminders" on public.birthday_reminders for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation posters" on public.birthday_posters for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation generations" on public.ai_generations for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation email logs" on public.email_logs for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation approvals" on public.approval_queue for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());
create policy "Tenant isolation activity" on public.activity_logs for all using (organization_id = public.current_organization_id()) with check (organization_id = public.current_organization_id());

create function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ declare org_id uuid; begin insert into organizations(name) values (coalesce(new.raw_user_meta_data->>'organization_name','My organization')) returning id into org_id; insert into users(id, organization_id, full_name, role) values (new.id, org_id, new.raw_user_meta_data->>'full_name', 'owner'); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
